# Generated by Django 2.2 on 2020-05-31 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='favorite',
            field=models.ManyToManyField(related_name='favorited_book', to='books_app.User'),
        ),
    ]
